library(swamp)
library(stringr)
library(ramify)
library(plyr)
con <- file("top_500_genes_multiclass.txt", "r")
line = readLines(con, 1)
tmp <- str_split(line, ",")
tmp <- tmp[[1]]
tmp <- as.double(tmp)
tmp <- resize(tmp, nrow=500, ncol=177)
dis <- read.table("/Genomics/ogtr04/sealfon/patient_specific/MN_paper2/210922_RNA_seq_analysis/validation_cohort.txt", sep=",")
#tmp <- t(tmp)
tmp<-as.table(tmp)
rownames(dis) <- colnames(tmp)
names(dis) <- c("diagnosis")
colnames(tmp) <- rownames(dis)
dis$diagnosis <- revalue(dis$diagnosis, c("4 - FSGS" = "Other", "2 - MCD" = "Other", "3 - Other" = "Other"))
dis$diagnosis <- revalue(dis$diagnosis, c("1 - MN" = "MN"))
palette(c("#E34A33", "#FEE9C8"))

hca.plot(tmp,dis)
dev.copy(pdf, "hca_plot_validation_top500.pdf")
dev.off()